### ISSUE TITLE
GUI for Website Updates

### ISSUE THREAD

**Issue by mithintv** [mithintv/portfolio-react#10]
### Tasks
- [ ] Login page via url (no visible button on site)
- [ ] Login authentication and authorization
- [ ] View current projects, their descriptions and tags and images
