### ISSUE TITLE
Reverse Mobile Drawer

### ISSUE THREAD

**Issue by mithintv** [mithintv/portfolio-react#14]
### Tasks
- [x] Blur out on backdrop click
- [x] Drawer out on backdrop click
- [x] Conjoin hamburger and mobile nav bar
